# Generated by Django 3.2.6 on 2021-08-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_lead_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
